name: Build and Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build mimir-ai
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ vars.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
      BUNDLE_ANALYZE: ${{ vars.BUNDLE_ANALYZE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@soumarcelino"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .next/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyze Release
        if: false
        run: |
          yarn release --dry-run

      - name: Show Next Version
        run: |
          echo "Next Release Version: $NEXT_RELEASE_VERSION"

      - name: Bump Next Version
        if: ${{ env.NEXT_RELEASE_VERSION != '' }}
        run: yarn version --new-version $NEXT_RELEASE_VERSION --no-git-tag-version

      - name: Build Application
        if: false
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: ./out
      
      - name: Upload analyze artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analyze-artifacts
          path: .next/analyze

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build
    #environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        if: false
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: ./out

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Deploy to S3 Bucket
        if: false
        run: aws s3 sync ./out s3://mimir-ai-site --delete

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: deploy
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@soumarcelino"
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .next/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        run: |
          yarn release

      - name: Prepare Slack Message
        run: |
          echo "SLACK_PAYLOAD=$(echo '${{ env.RELEASE_BODY }}' | base64 --decode)" >> $GITHUB_ENV

      - name: Notify Slack
        if: success()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: 'incoming-webhook'
          payload: |
              {
                "text": "${{ env.SLACK_PAYLOAD }}",
                "version":  "${{ env.NEXT_RELEASE_VERSION }}",
                "user": "${{ github.actor }}",
              }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
